sudo: false
language: node_js
node_js:
  - "4"
  - "5"
install:
  - npm install
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f0bf0d33d2af82753e00
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
